CREATE SCHEMA DBMS_JOBS;

CREATE SEQUENCE DBMS_JOBS.JOB_SEQ;

CREATE TABLE DBMS_JOBS.JOB_GROUP(
   GROUP_ISN         SMALLINT,
   GROUP_NAME        VARCHAR(32),
   PRIORITY          SMALLINT,
   MAX_JOBS          SMALLINT
) DISTRIBUTED BY (GROUP_ISN);

CREATE TABLE DBMS_JOBS.JOB_QUEUE(
   JOB_ISN           INT,
   JOB_ATTEMPT       SMALLINT,
   JOB_ATTEMPT_LIMIT SMALLINT,
   JOB_SUBMIT_DTTM   TIMESTAMP,
   JOB_GROUP         SMALLINT,
   JOB_SESSION_ID    INT,
   JOB_SESSION_START_DTTM TIMESTAMP,
   JOB_STATUS        VARCHAR(5),
   JOB_CODE          VARCHAR(3000)
) DISTRIBUTED BY (JOB_ISN)
PARTITION BY LIST (JOB_STATUS)(
   PARTITION new_running VALUES('NEW', 'RUN'),
   PARTITION end_failed  VALUES('END', 'FLD')
);

CREATE TABLE DBMS_JOBS.JOB_LOG(
   JOB_ISN           INT,
   JOB_ATTEMPT       SMALLINT,
   JOB_MESSAGE       TEXT,
   JOB_MESSAGE_DTTM  TIMESTAMP DEFAULT current_timestamp
) DISTRIBUTED BY (JOB_ISN);

CREATE TABLE DBMS_JOBS.JOB_SYNC(
   LOCKED smallint
) DISTRIBUTED BY (LOCKED);
