create view ais.vy_subacc_plan(
ISN, PARENTISN, CODE, ID, N_CHILDREN, SHORTNAME, FULLNAME, DATEBEG, DATEEND, 
DATEMOD, DATEQUIT, EMPLISN, EMPLNAME, ACTIVE, HUMANFLAG, DEPTFLAG, REMARK, 
UPDATED, UPDATEDBY, BUHGRANTISN, BUHGRANTUPDATED, CURRISN, ACTPAS) as

               SELECT  --+use_nl(BA BG S) ordered
 BA.ISN, BA.PARENTISN, BA.CODE, BA.ID, BA.N_CHILDREN,
 BA.SHORTNAME, BA.FULLNAME,
 BA.DATEBEG , BA.DATEEND  , BG.BUHBEG AS DATEMOD, BA.DATEQUIT,
 BA.EMPLISN , Substr(InitCap(S.SHORTNAME),1,40) as EMPLNAME,
 BA.ACTIVE, BA.HUMANFLAG , BA.DEPTFLAG , BA.REMARK , BA.UPDATED, BA.UPDATEDBY,
 BG.isn BUHGRANTISN, BG.updated BUHGRANTUPDATED, BA.CURRISN --06/02/2013 KOTOV/AS/EPAM Добавил CURRISN
 , BA.ACTPAS
FROM ais.BUHSUBACC BA left join ais.BUHGRANT BG on BA.ISN = BG.CLASSISN AND BG.STATUS = 'B' AND BG.EMPLISN = 490
left join ais.SUBJECT S on BA.EMPLISN=S.ISN