-- View definition script STORAGES.V_REPBUH2RESECTION for Greenplum
-- Generated by (c) Ispirer SQLWays 6.0 Build 2145 32bit Licensed to ak
-- Timestamp: Thu Feb 20 08:25:04 2014

--Commented source
----CREATE VIEW STORAGES.V_REPBUH2RESECTION(AGRISN,BODYISN,STATCODE,DATEVAL,RPTGROUPISN,MOTIVGROUPISN,BUDGETGROUPISN,RPTCLASS,RPTCLASSISN,REFUNDISN,REFUNDEXTISN,BUHCURRISN,SAGROUP,BUHAMOUNTRUB,BUHAMOUNTUSD,BUHAMOUNT,AMOUNTRUB,AMOUNTUSD,AMOUNT,REISN,REAGRCLASSISN,SECTISN,SHARENEORIG,REINSURANCEPERIODPC,SECTPC,BUHISN) AS
----SELECT a.agrisn, a.bodyisn, max(a.statcode) AS statcode, max(a.dateval) AS dateval, a.rptgroupisn, a.motivgroupisn,
----       a.budgetgroupisn, a.rptclass, a.rptclassisn, a.refundisn, a.refundextisn,
----       max(a.buhcurrisn) AS buhcurrisn, max(a.sagroup) AS sagroup, max(a.buhamountrub) AS buhamountrub,
----       max(a.buhamountusd) AS buhamountusd, max(a.buhamount) AS buhamount,
----       sum(a.amountrub*a.sectpc) AS amountrub,
----       sum(a.amountusd*a.sectpc)AS amountusd,
----       sum(a.amount*a.sectpc) AS amount,
----       max(a.reisn) AS reisn,
----       max(a.reagrclassisn) AS reagrclassisn,
----       a.sectisn,
----       a.shareneorig,
----       max(a.reinsuranceperiodpc) AS reinsuranceperiodpc,
----       max(a.sectpc) AS sectpc,
----       MAX(a.buhisn) AS buhisn
----FROM (
----      SELECT --+ ordered use_nl ( a re ra s ) index ( re X_REPAGR_AGR ) index ( ra  X_REPAGR_AGR )
----             a.agrisn, a.rptgroupisn, a.amountrub, a.amountusd, a.amount, a.statcode,
----             a.refundisn, a.refundextisn, a.bodyisn, a.dateval, a.motivgroupisn,
----             a.reinsuranceperiodpc, a.shareneorig, a.reagrclassisn, a.sectisn,
----             a.reisn, /*1/COUNT(sectisn) over (PARTITION BY a.buhisn) EGAO 26.04.2013 */1 AS sectpc, a.buhamountrub, a.buhamountusd, a.buhamount,
----             a.buhcurrisn, a.sagroup, a.budgetgroupisn, a.rptclass, a.rptclassisn, a.buhisn
----      FROM (
----            WITH
----                 x AS (
----                       SELECT x.*
----                       FROM (
----                             SELECT --+ index ( x X_REP_AGRRE_AGR ) ordered use_nl ( x re ra )
----                                    DISTINCT x.agrisn, x.condisn, x.reisn, x.sectisn,
----                                             CASE
----                                               WHEN re.datebase='I' THEN 1
----                                               ELSE (least(trunc(x.sdateend), trunc(ra.dateend))-greatest(trunc(x.sdatebeg), trunc(ra.datebeg))+1)/(trunc(ra.dateend)-trunc(ra.datebeg)+1)
----                                             END AS reinsuranceperiodpc,
----                                             CASE re.classisn
----                                               WHEN 9058 THEN nvl(x.shareneorig/100, 1)
----                                               ELSE 1
----                                             END AS shareneorig,
----                                             re.classisn AS reagrclassisn
----
----                             FROM rep_agrre x, repagr re, repagr ra
----                             WHERE x.agrisn>shared_system.GetParamN('minagrisn') AND x.agrisn<=shared_system.GetParamN('maxagrisn')
----                               AND re.agrisn=x.reisn
----                               AND ra.agrisn=x.agrisn
----                            ) x
----                       WHERE x.reinsuranceperiodpc>0
----                      ),
----                 a AS (
----                       SELECT --+ index ( bc X_REPBUH2COND_AGRISN ) ordered use_nl ( x bc ) no_merge ( x )
----                              bc.agrisn, bc.condisn, bc.rptgroupisn, bc.refundisn, bc.statcode,
----                              bc.refundextisn, bc.bodyisn, bc.motivgroupisn, bc.budgetgroupisn, bc.rptclass, bc.rptclassisn,
----                              MAX(bc.isn) AS buhisn,
----                              MAX(bc.dateval) AS dateval,
----                              MAX(bc.buhamountrub) AS buhamountrub,
----                              MAX(bc.buhamountusd) AS buhamountusd,
----                              MAX(bc.buhamount) AS buhamount,
----                              MAX(bc.buhcurrisn) AS buhcurrisn,
----                              MAX(bc.sagroup) AS sagroup,
----                              SUM(bc.amountusd) AS amountusd,
----                              SUM(bc.amount) AS amount,
----                              SUM(bc.amountrub) AS amountrub
----                       FROM (SELECT DISTINCT agrisn FROM x) x, repbuh2cond bc
----                       WHERE bc.agrisn=x.agrisn
----                         AND bc.statcode IN (38, 34, 220, 24)
----                         AND bc.sagroup IN (1, 3)
----                         AND NVL(bc.amountrub,0)<>0
----                       GROUP BY bc.agrisn, bc.condisn, bc.rptgroupisn, bc.refundisn, bc.statcode,
----                                bc.refundextisn, bc.bodyisn, bc.motivgroupisn, bc.budgetgroupisn, bc.rptclass, bc.rptclassisn
----                       HAVING SUM(bc.amountrub)<>0
----                      )
----
----            SELECT --+ use_hash ( a x )
----                   a.*, x.sectisn, x.reisn, x.shareneorig, x.reagrclassisn, x.reinsuranceperiodpc
----            FROM a, x
----            WHERE x.agrisn=a.agrisn
----              AND x.condisn IS NULL
----            UNION
----            SELECT --+ use_hash ( a x )
----                   a.*, x.sectisn, x.reisn, x.shareneorig, x.reagrclassisn, x.reinsuranceperiodpc
----            FROM a, x
----            WHERE x.agrisn=a.agrisn
----              AND x.condisn IS NOT NULL
----              AND x.condisn=a.condisn
----
----           ) a) a
----GROUP BY a.agrisn,
----         a.bodyisn,
----         a.rptgroupisn,
----         a.motivgroupisn,
----         a.budgetgroupisn, a.rptclass, a.rptclassisn, a.refundisn, a.refundextisn,
----         a.sectisn,
----         a.shareneorig
----;

 --+ index ( x X_REP_AGRRE_AGR ) ordered use_nl ( x re ra )
                                     --+ index ( bc X_REPBUH2COND_AGRISN ) ordered use_nl ( x bc ) no_merge ( x )
CREATE VIEW STORAGES.V_REPBUH2RESECTION(AGRISN,BODYISN,STATCODE,DATEVAL,RPTGROUPISN,MOTIVGROUPISN,BUDGETGROUPISN,RPTCLASS,RPTCLASSISN,REFUNDISN,REFUNDEXTISN,BUHCURRISN,SAGROUP,BUHAMOUNTRUB,BUHAMOUNTUSD,BUHAMOUNT,AMOUNTRUB,AMOUNTUSD,AMOUNT,REISN,REAGRCLASSISN,SECTISN,SHARENEORIG,REINSURANCEPERIODPC,SECTPC,BUHISN) AS
SELECT a.agrisn, a.bodyisn, max(a.statcode) AS statcode, max(a.dateval) AS dateval, a.rptgroupisn, a.motivgroupisn,
       a.budgetgroupisn, a.rptclass, a.rptclassisn, a.refundisn, a.refundextisn,
       max(a.buhcurrisn) AS buhcurrisn, max(a.sagroup) AS sagroup, max(a.buhamountrub) AS buhamountrub,
       max(a.buhamountusd) AS buhamountusd, max(a.buhamount) AS buhamount,
       sum(a.amountrub*a.sectpc) AS amountrub,
       sum(a.amountusd*a.sectpc)AS amountusd,
       sum(a.amount*a.sectpc) AS amount,
       max(a.reisn) AS reisn,
       max(a.reagrclassisn) AS reagrclassisn,
       a.sectisn,
       a.shareneorig,
       max(a.reinsuranceperiodpc) AS reinsuranceperiodpc,
       max(a.sectpc) AS sectpc,
       MAX(a.buhisn) AS buhisn
FROM (
      SELECT --+ ordered use_nl ( a re ra s ) index ( re X_REPAGR_AGR ) index ( ra  X_REPAGR_AGR )
             a.agrisn, a.rptgroupisn, a.amountrub, a.amountusd, a.amount, a.statcode,
             a.refundisn, a.refundextisn, a.bodyisn, a.dateval, a.motivgroupisn,
             a.reinsuranceperiodpc, a.shareneorig, a.reagrclassisn, a.sectisn,
             a.reisn, /*1/COUNT(sectisn) over (PARTITION BY a.buhisn) EGAO 26.04.2013 */1 AS sectpc, a.buhamountrub, a.buhamountusd, a.buhamount,
             a.buhcurrisn, a.sagroup, a.budgetgroupisn, a.rptclass, a.rptclassisn, a.buhisn
      FROM (
            WITH
                 x AS (
                       SELECT x.*
                       FROM (
                             SELECT --+ index ( x X_REP_AGRRE_AGR ) ordered use_nl ( x re ra )
                                    DISTINCT x.agrisn, x.condisn, x.reisn, x.sectisn,
                                             CASE
                                               WHEN re.datebase='I' THEN 1
                                               ELSE extract(days from ((least(date_trunc('day',x.sdateend), date_trunc('day',ra.dateend))-greatest(date_trunc('day',x.sdatebeg), date_trunc('day',ra.datebeg))+interval '1 day')))/extract(days from ((date_trunc('day',ra.dateend)-date_trunc('day',ra.datebeg)+interval '1 day')))
                                             END AS reinsuranceperiodpc,
                                             CASE re.classisn
                                               WHEN 9058 THEN coalesce(x.shareneorig/100, 1)
                                               ELSE 1
                                             END AS shareneorig,
                                             re.classisn AS reagrclassisn

                             FROM storages.rep_agrre x, STORAGE_SOURCE.REPAGR re, STORAGE_SOURCE.REPAGR ra
                             WHERE x.agrisn>shared_system.GetParamN('minagrisn') AND x.agrisn<=shared_system.GetParamN('maxagrisn')
                               AND re.agrisn=x.reisn
                               AND ra.agrisn=x.agrisn
                            ) x
                       WHERE x.reinsuranceperiodpc>0
                      ),
                 a AS (
                       SELECT --+ index ( bc X_REPBUH2COND_AGRISN ) ordered use_nl ( x bc ) no_merge ( x )
                              bc.agrisn, bc.condisn, bc.rptgroupisn, bc.refundisn, bc.statcode,
                              bc.refundextisn, bc.bodyisn, bc.motivgroupisn, bc.budgetgroupisn, bc.rptclass, bc.rptclassisn,
                              MAX(bc.isn) AS buhisn,
                              MAX(bc.dateval) AS dateval,
                              MAX(bc.buhamountrub) AS buhamountrub,
                              MAX(bc.buhamountusd) AS buhamountusd,
                              MAX(bc.buhamount) AS buhamount,
                              MAX(bc.buhcurrisn) AS buhcurrisn,
                              MAX(bc.sagroup) AS sagroup,
                              SUM(bc.amountusd) AS amountusd,
                              SUM(bc.amount) AS amount,
                              SUM(bc.amountrub) AS amountrub
                       FROM (SELECT DISTINCT agrisn FROM x) x, storages.repbuh2cond bc
                       WHERE bc.agrisn=x.agrisn
                         AND bc.statcode IN (38, 34, 220, 24)
                         AND bc.sagroup IN (1, 3)
                         AND coalesce(bc.amountrub,0)<>0
                       GROUP BY bc.agrisn, bc.condisn, bc.rptgroupisn, bc.refundisn, bc.statcode,
                                bc.refundextisn, bc.bodyisn, bc.motivgroupisn, bc.budgetgroupisn, bc.rptclass, bc.rptclassisn
                       HAVING SUM(bc.amountrub)<>0
                      )

            SELECT --+ use_hash ( a x )
                   a.*, x.sectisn, x.reisn, x.shareneorig, x.reagrclassisn, x.reinsuranceperiodpc
            FROM a, x
            WHERE x.agrisn=a.agrisn
              AND x.condisn IS NULL
            UNION
            SELECT --+ use_hash ( a x )
                   a.*, x.sectisn, x.reisn, x.shareneorig, x.reagrclassisn, x.reinsuranceperiodpc
            FROM a, x
            WHERE x.agrisn=a.agrisn
              AND x.condisn IS NOT NULL
              AND x.condisn=a.condisn

           ) a) a
GROUP BY a.agrisn,
         a.bodyisn,
         a.rptgroupisn,
         a.motivgroupisn,
         a.budgetgroupisn, a.rptclass, a.rptclassisn, a.refundisn, a.refundextisn,
         a.sectisn,
         a.shareneorig
;